# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e927d7fa7aa5861135f23b282e1f29ca55fa051b9335bec60ccdcdd7bfb4d1e47df23ee54105a3685e66b12fb2b1ad6d268b5fb0e855f894b76f20ea752260

test:
  secret_key_base: 0c4a3546d819b8d1653648aba62867a88cd1ad0bf7a11391ab8b907f2b0a698e8db544f4c713cb4ffd79b211c1e853edb05dc1f3ba1dbc676a52383f95ed9819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
